"""Update User model

Revision ID: e76f8ce6c81a
Revises: 5dfb225c1db0
Create Date: 2023-11-29 01:31:09.333097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76f8ce6c81a'
down_revision = '5dfb225c1db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('unique_email_constraint', ['email'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    """
    ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), nullable=False))
        # batch_op.drop_constraint('unique_email_constraint', type_='unique')
        # batch_op.drop_column('password_hash')
        # batch_op.drop_column('email')

    # ### end Alembic commands ###
    """
